# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Voatotype
email: your-email@domain.com
# description: Modular HTML/CSS for Voat
baseurl: "/Voatotype" # the subpath of your site, e.g. /blog
url: "https://mijowa.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: expanded

# Serve settings
